### ISSUE TITLE
Offline Suggestions with parity to what the web does

### ISSUE THREAD

**Issue by alexshepard** [inaturalist/iNaturalistMLWork#112]
https://github.com/inaturalist/vision-camera-plugin-inatvision/issues/9

https://docs.google.com/document/d/1wdKrG8h6hkbRUl2dKBMoHj1yaFMFJ1CxkYURrxg2CJc/edit#heading=h.suak1gm6cfpa

**Comment by alexshepard** [comment]
Abhas writes: 
There are basically 3 states that can happen on suggestions:
1. api has provided a common ancestor and there is no leaf node suggestion with combined score higher than .78. in this case, we show common ancestor as top id suggestion (same as the web)
2. api does not provide a common ancestor and there is no leaf node suggestion with a combined score higher than .78. in this case, show this message under the top id suggestion section: “We’re not confident enough to make a top ID suggestion, but here are some other suggestions:” (same as web).
3. there is a leaf node suggestion with a combined score higher than .78. in this case, show the leaf node suggestion with the highest score above .78 as top id suggestion (new state)

**Comment by alexshepard** [comment]
Abhas provides some justification / context:

State number 3 is different from web and is an experiment on mobile because it can often be dissatisfying to get common ancestor “Genus Gingko” and only have one leaf node suggestion “Gingko biloba.” – I think in these cases, showing the leaf node under Top ID suggestion is more satisfying for a user.

We’re using .78 or higher to show a leaf node here because the common ancestor always has a combined score of .78 or higher, and corresponds to having something like 90% accuracy. If a leaf node has a combined score of higher than .78, we hypothesize that it should similarly have a high accuracy, and thus is reasonable to show under the Top ID suggestion section.

**Comment by loarie** [comment]
not necessary
