### ISSUE TITLE
Logging for NL Search

### ISSUE THREAD

**Issue by alexshepard** [inaturalist/iNaturalistMLWork#75]

**Comment by loarie** [comment]
from the Jun 12 meeting:
Re: the search #94 now has 
user_id (if available),
search_term, (query)
taxon_id, (filter)
in the Kibana logs for 30 days
whats needed is a more permanent store

Re: the submit flow, we are storing
user_id
search term
taxon_id
page
votes (which includes images)
in the db

**Comment by loarie** [comment]
within 30 days of launch, we'll schedule a meeting with research collaborators
that will include exported data
based on that meeting will develop plan/strategy for handling data beyond that first month
